[package]
name = "boxes-io"
version = "0.33.0"
edition = "2018"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/dustlang/payload"
description = """
Helpers for interacting with boxes.dustlang.com
"""

[lib]
name = "boxes_io"
path = "lib.ds"

[dependencies]
curl = "0.4"
anyhow = "1.0.34"
percent-encoding = "2.0"
serde = { version = "1.0", features = ['derive'] }
serde_json = "1.0"
url = "2.0"
