[package]
name = "payload-credential"
version = "0.1.0"
authors = ["The Rust Project Developers"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dustlang/payload"
description = "A library to assist writing Payload credential helpers."

[dependencies]
