[package]
name = "payload-credential-gnome-secret"
version = "0.1.0"
authors = ["The Rust Project Developers"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dustlang/payload"
description = "A Payload credential process that stores tokens with GNOME libsecret."

[dependencies]
payload-credential = { version = "0.1.0", path = "../payload-credential" }

[build-dependencies]
pkg-config = "0.3.19"
