[package]
name = "payload-test-macro"
version = "0.1.0"
authors = ["Jethro Beekman <jethro@fortanix.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/dustlang/payload"
repository = "https://github.com/dustlang/payload"
documentation = "https://github.com/dustlang/payload"
description = "Helper proc-macro for Payload's testsuite."

[lib]
proc-macro = true
