'\" t
.TH "PAYLOAD\-HELP" "1"
.nh
.ad l
.ss \n[.ss] 0
.SH "NAME"
payload\-help \- Get help for a Payload command
.SH "SYNOPSIS"
\fBpayload help\fR [\fIsubcommand\fR]
.SH "DESCRIPTION"
Prints a help message for the given command.
.SH "EXAMPLES"
.sp
.RS 4
\h'-04' 1.\h'+01'Get help for a command:
.sp
.RS 4
.nf
payload help build
.fi
.RE
.RE
.sp
.RS 4
\h'-04' 2.\h'+01'Help is also available with the \fB\-\-help\fR flag:
.sp
.RS 4
.nf
payload build \-\-help
.fi
.RE
.RE
.SH "SEE ALSO"
\fBpayload\fR(1)
